### ISSUE TITLE
Port all the CI Bells and Whistles Here Too

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMakePPLang#32]
Basically the same as CMakePP/CMakeTest#45. This repo should have CI for:

- [x] #73
- [x] #75
- [x] building documentation

**Comment by zachcran** [comment]
Has the "building documentation" task already been completed? We are using the reusable workflows available for documentation from `CMakePP/.github` now.

**Comment by ryanmrichard** [comment]
https://cmakepp.github.io/CMakePPLang/api/index.html doesn't show any API documentation at the moment.

**Comment by zachcran** [comment]
Oh, I screwed up some of the paths in the reusable workflow when I was writing it. I figured out the issues and will fix them over there.

**Comment by zachcran** [comment]
The API documentation is now showing up at https://cmakepp.github.io/CMakePPLang/api/index.html, so I think that is the last task complete here.
