### ISSUE TITLE
API documentation missing on website

### ISSUE THREAD

**Issue by zachcran** [CMakePP/CMakePPLang#39]
**Describe the bug**
The API documentation is not appearing on the documentation website at https://cmakepp.github.io/CMakePPLang/api/index.html. I do not think there is a workflow set up yet to generate it.

**To Reproduce**
1. Go to https://cmakepp.github.io/CMakePPLang/.
2. Click on the "API" option on the side bar.
3. The API page is loaded, but empty.

**Expected behavior**
I expect to see documentation about the API on this page.

**Comment by ryanmrichard** [comment]
This duplicates #30, but is more descriptive so I'll keep this one.
