### ISSUE TITLE
Error 404 when accessing 'Contributing' page on CMakePPLang website

### ISSUE THREAD

**Issue by Xyphenore** [CMakePP/CMakePPLang#93]
**Describe the bug**
I encountered a 404 error when trying to access the 'Contributing' page on the CMakePPLang website.

**To Reproduce**
1. Go to https://cmakepp.github.io/CMakePPLang/index.html
2. Click on 'Contributing' in the navigation bar on the left.
3. Encounter a 404 error.

**Expected behavior**
The page should be displayed, providing information about the rules for contributing to the project. Alternatively, if the page does not exist, the 'Contributing' link should be removed from the navigation bar.

**Additional context**
The URL linked to the 'Contributing' button is https://cmakepp.github.io/.github/code_of_conduct/index.html.

**Comment by ryanmrichard** [comment]
@Xyphenore Thanks for catching this! For what it's worth, that 404 is supposed to link to the HTML version of [this](https://github.com/CMakePP/.github/blob/main/CODE_OF_CONDUCT.rst).

@zachcran I think the problem on this one is that the `.github` repo's documentation does not appear to be building. Do you think you'll have time to look at this in the next several days?

**Comment by zachcran** [comment]
@ryanmrichard I'll take a look at this today!

**Comment by zachcran** [comment]
Give it a few minutes to generate the documentation, then the link should be fixed. I will reopen this issue if the fix didn't work.

**Comment by ryanmrichard** [comment]
This is still a 404.

**Comment by zachcran** [comment]
Sorry, since the latest change came from my fork, the workflow rebuilding the documentation website failed.

@Xyphenore The website should be updated now!
